---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: git
  labels:
    name: git
spec:
  serviceName: git
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: git
      labels:
        name: git
    spec:
      volumes:
      - name: git
        hostPath:
          path: /data/git
      containers:
        - name: git
          image: registry-vpc.cn-shanghai.aliyuncs.com/papillonyispace/openimages:git-server
          imagePullPolicy: Always
          ports:
            - containerPort: 22
          resources:
            limits:
              cpu: 0.5
              memory: 500Mi
          volumeMounts:
          - name: git
            mountPath: /data
---
apiVersion: v1
kind: Service
metadata:
  name: git-server
  labels:
    name: git
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
  selector:
    name: git
