apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: portia
  labels:
    name: portia
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: portia
    spec:
      containers:
      - name: portia
        image: scrapinghub/portia
        ports:
        - containerPort: 9001
        volumeMounts:
        - mountPath: /app/data/projects
          name: portia
      volumes:
        - name: portia
          hostPath:
            path: /data/portia
      nodeSelector:
        master: false
---
apiVersion: v1
kind: Service
metadata:
  name: portia
  labels:
    name: portia
spec:
  ports:
  - port: 9001
    targetPort: 9001
  selector:
    name: portia
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: portia
          servicePort: 9001
