{{- if .Values.Istio.deploy_base_config }}
{{- if .Values.global.auth_enabled }}
{{- if .Values.global.ca_demo }}
{{- $istio_namespace := .Values.global.namespace }}
{{- $ca_hub := .Values.global.ca_hub }}
{{- $ca_tag := .Values.global.ca_tag }}
################################
# Istio-CA single namespace
################################
# This CA only issues certs/keys for the namespace it runs in.
# For demo only. Please use istio-cluster-ca.yaml for real-world use cases.
# Service account CA runs in.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ca-service-account
  namespace: {{ $istio_namespace }}
---
# Istio CA
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: istio-ca
  namespace: {{ $istio_namespace }}
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        istio: istio-ca
    spec:
      serviceAccountName: istio-ca-service-account
      containers:
      - name: istio-ca
        image: {{$ca_hub}}/istio-ca:{{$ca_tag}}
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
---
{{- end }}
{{- end }}
{{- end }}
